apiVersion: security.kubeideas.io/v1
kind: LinkedSecret
metadata:
  name: aws-plain-example1
spec:
  provider: AWS
  providerSecretFormat: PLAIN
  providerOptions:
    secret: <AWS-SECRET-NAME>
    region: <AWS-SECRET-RESOURCE-REGION>
    version: AWSCURRENT 
  secretName: mysecret-aws-plain-example1
  schedule: "@every 10m"
 
