apiVersion: security.kubeideas.io/v1
kind: LinkedSecret
metadata:
  name: google-json-example1
spec:
  provider: Google
  providerSecretFormat: JSON
  providerOptions:
    project: <GCP-PROJECT-ID>
    secret: <GCP-SECRET-NAME>
    version: latest  
  secretName: mysecret-google-json-example1
  schedule: "@every 10m"
 
