# This patch inject secret with AWS credentials access key and secret for controller manager authentication on AWS API 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: IBM_SERVICE_API_KEY
          valueFrom:
            secretKeyRef:
              key: IBM_SERVICE_API_KEY
              name: ibm-credentials
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi 