{{- if .Values.aws.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data: 
  AWS_ACCESS_KEY_ID: {{ .Values.aws.awsAccessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.awsSecretAccessKey | b64enc }}
{{- end }}