{{- if .Values.azure.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: azure-credentials
type: Opaque
data: 
  AZURE_TENANT_ID: {{ .Values.azure.azureTenantId | b64enc }}
  AZURE_CLIENT_ID: {{ .Values.azure.azureClientId | b64enc }}
  AZURE_CLIENT_SECRET: {{ .Values.azure.azureClientSecret | b64enc }}
{{- end }}