apiVersion: security.kubeideas.io/v1
kind: LinkedSecret
metadata:
  name: google-plain-example1
spec:
  provider: Google
  providerSecretFormat: PLAIN
  providerOptions:  
    project: <GCP-PROJECT-ID>
    secret: <GCP-SECRET-NAME>
    version: latest  
  secretName: mysecret-google-plain-example1
  schedule: "@every 10m"
 
