# permissions for end users to view linkedsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: linkedsecret-viewer-role
rules:
- apiGroups:
  - security.kubeideas.io
  resources:
  - linkedsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - security.kubeideas.io
  resources:
  - linkedsecrets/status
  verbs:
  - get
