# permissions for end users to edit linkedsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: linkedsecret-editor-role
rules:
- apiGroups:
  - security.kubeideas.io
  resources:
  - linkedsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.kubeideas.io
  resources:
  - linkedsecrets/status
  verbs:
  - get
