apiVersion: security.kubeideas.io/v1
kind: LinkedSecret
metadata:
  name: ibm-json-example1
spec:
  provider: IBM
  providerSecretFormat: JSON
  providerOptions:
    secretManagerInstanceId: <SECRET-MANAGER-INSTANCE-UUID>
    secretId: <SECRET-UUID>
    region: us-east   
  secretName: mysecret-ibm-json-example1
  schedule: "@every 10m"
 
