apiVersion: security.kubeideas.io/v1
kind: LinkedSecret
metadata:
  name: ibm-plain-example1
spec:
  provider: IBM
  providerSecretFormat: PLAIN
  providerOptions:
    secretManagerInstanceId: <SECRET-MANAGER-INSTANCE-UUID>
    secretId: <SECRET-UUID>
    region: us-east
  secretName: mysecret-ibm-plain-example1
  schedule: "@every 10m"
 
