apiVersion: security.kubeideas.io/v1
kind: LinkedSecret
metadata:
  name: azure-json-example1
spec:
  deployment: <DEPLOYMENT-NAME>
  provider: Azure
  providerDataFormat: JSON
  providerOptions:
    keyvault: <AZURE-KEYVAULT-NAME>
    secret: <AZURE-SECRET-NAME>
    #version: <AWZURE-SECRET-VERSION-ID> 
  secretName: mysecret-azure-json-example1
  schedule: "@every 10m"
 
