apiVersion: security.kubeideas.io/v1
kind: LinkedSecret
metadata:
  name: azure-json-example2
spec:
  provider: Azure
  providerSecretFormat: JSON
  providerOptions:
    keyvault: <AZURE-KEYVAULT-NAME>
    secret: <AZURE-SECRET-NAME>
    #version: <AWZURE-SECRET-VERSION-ID> 
  secretName: mysecret-azure-json-example2
  schedule: "* */10 * * * *"
 
