apiVersion: security.kubeideas.io/v1
kind: LinkedSecret
metadata:
  name: plain-example2
spec:
  provider: Google
  providerDataFormat: PLAIN
  providerOptions:
    project: <GCP-PROJECT-ID>
    secret: <GCP-SECRET-NAME>
    version: latest  
  secretName: mysecret-plain-secret2
  schedule: "*/20 * * * * *"
 
